### ISSUE TITLE
Add dues functionality to boiler books

### ISSUE THREAD

**Issue by grantg012** [PurdueIEEE/boilerbooks#117]

**Comment by hadiahmed098** [comment]
Is this something we want in boilerbooks or the admin panel?

**Comment by grantg012** [comment]
I was thinking it would be nice if it was integrated with boiler books. That way:

- People could see if they have paid dues
- Officers can have their own logins
- The treasurer (and no one else) can mark dues as paid
- The amount of collected dues can be listed alongside the deposited amount

**Comment by hadiahmed098** [comment]
OK that reasoning makes sense, I think the accounting features would be a great benefit alone. I suggest you wait on this and see if  that PWA or Flask/Django/Node rewrite we were planning on maybe doing with @avaidyam actually happens.

**Comment by grantg012** [comment]
Gotcha. I might get started on it in PHP just since I'm slightly more familiar with that and it's a little easier to port things sometimes than to write them. But I got plenty of other things to do in the meantime too.
