### ISSUE TITLE
Pull css and js into repo

### ISSUE THREAD

**Issue by grantg012** [PurdueIEEE/boilerbooks#128]
CDN (Content Delivery Network). You load Bootstrap and JQuery from script/link tags. It's best to self host this since we cannot guarantee the veracity of what we request nor can we ensure the resources stay online. Also, the version you import could change at anytime with breaking effects.

If we pull them onto the server all these issues are resolved. I'll have to look at how integrated they are but this might be worthy of a separate PR. @grantg012

_Originally posted by @hadiahmed098 in https://github.com/PurdueIEEE/boilerbooks/issues/127#issuecomment-952529909_

**Comment by hadiahmed098** [comment]
We are probably fine just using CDNs here, not worth the hassle of pulling in the files ourselves.
