### ISSUE TITLE
Add back Dues functionality

### ISSUE THREAD

**Issue by hadiahmed098** [PurdueIEEE/boilerbooks#145]
Some dues functionality was removed in v2, needs to be added back.

**Comment by grantg012** [comment]
(commenting here so I join the issue)

**Comment by hadiahmed098** [comment]
So from my recollection and understanding after talking with Chris, the following needs to be added back:

* Allow all officers to enter a dues roster
* Allow treasurer to mark dues as 'Paid' or 'Unpaid'
* Allow treasurers to view reported dues income vs expected dues income

Is that everything?

**Comment by hadiahmed098** [comment]
(I know there was a way for members to add themselves but I'd rather centralize dues modification to officer accounts)

**Comment by grantg012** [comment]
Yeah those are the main three. It's nice for individuals to be able to see if they've been marked as paid and to add themselves to committees, but not a huge deal. The number of IEEE members is far greater than the number of members with boiler books accounts
