### ISSUE TITLE
Viewing your own purchase sorting order

### ISSUE THREAD

**Issue by grantg012** [PurdueIEEE/boilerbooks#153]
Looking at your own purchases shows all pending and denied purchases then your approved purchases from oldest to newest. Ideally people could 1- forward/reverse sort them by date (something I think the old datatables could do) and 2- the purchases would be in order of when they were started so someone can see their most recent requests and approved ones easily.

![image](https://user-images.githubusercontent.com/27533436/162516752-f8b5c692-96bd-4aea-9eae-d4dd213b5c3f.png)

**Comment by hadiahmed098** [comment]
By "when they were started" do you mean chronological order or modification order?

i.e. should most recent modified show up first or chronologically oldest purchase?

**Comment by hadiahmed098** [comment]
Also yeah the blank ones showing up earlier is a bug with how I sort the array, I will swap the sort index to the purchaseID

**Comment by grantg012** [comment]
I would some variant of newest first (either started on date or last modified date)

**Comment by hadiahmed098** [comment]
Resolved with eaa48ebb0a10f1f77235ee8daa5d14293a7923db
