### ISSUE TITLE
Weakly limit how much someone can increase a purchase

### ISSUE THREAD

**Issue by grantg012** [PurdueIEEE/boilerbooks#155]
There's no max to these inputs. Obviously someone can just edit the html and send something higher, so doing a check like you have on the server is needed. But this could help prevent inadvertent over-increases.

https://github.com/PurdueIEEE/boilerbooks/blob/master/ui/src/views/purchase/PurchaseApprove.vue#L46
https://github.com/PurdueIEEE/boilerbooks/blob/master/ui/src/views/purchase/PurchaseComplete.vue#L38

**Comment by hadiahmed098** [comment]
One note with this is with IEEE-754, the amount it limits on the form, the amount it limits on the server, and the actual max amount may be different due to funky rounding.
