### ISSUE TITLE
Non-monetary donations break financials reporting

### ISSUE THREAD

**Issue by hadiahmed098** [PurdueIEEE/boilerbooks#159]
When a non-monetary source is entered as 'Income', i.e. an item donation, the amount of the item donation still shows up as income that can be spent. This is incorrect as that money does not exist in the account but rather as an expected value of the item being donated.

Further, with discount donations, the purchase entry would reflect the actual price paid and not necessarily the total price before discounts. This can again cause money that does not exist to show up as available to spend.

If not corrected, an audit will uncover significant deviations from the actual balance present. If corrected improperly, old income entries that did not cause 'fake' money to appear will now subtract a valid balance from the total.

**Comment by hadiahmed098** [comment]
From Slack: "Could we change it to two donation types, like 'monetary' income and 'non-monetary' donations?" - Matthieu

**Comment by hadiahmed098** [comment]
From Slack: "The issue I see with this approach is that non-cash/material donations do not have an associated value. We need these to have an associated value for the purpose of claiming non-cash/material donations against certain grants, which is why I entered donations in the first place. 

I do not see any issue with adding the donation and then adding a counter balance purchase, as Hadi originally suggested" - Charles D'Onofrio

**Comment by hadiahmed098** [comment]
@grantg012 I know you have the most experience using and working on Boiler Books. How should we be properly handling non-monetary income like discounts and items?

**Comment by grantg012** [comment]
Ok there's a lot so going piecemeal:

> When a non-monetary source is entered as 'Income'

First issue. Non-monetary sources should be `Discount`s. I think there is an "issue" that we don't have a more explicit item/non-cash category.

**Comment by grantg012** [comment]
Then I think to fulfill Charles' request, there could/should be another total (really there could be a couple more on the Committee breakdown page).
So the changes I'd see:
* Income -> Cash Income
* Add a Non-cash income
* Add a income sum (cash + non-cash)
* Also add an "outstanding" income. This was something I think Matthieu had asked for a while back when expected income wasn't counted for a total. But add something to total up income that's expected, but hasn't yet been received

**Comment by grantg012** [comment]
@hadiahmed098 Are you currently summing donations as part of a committee's income?

**Comment by hadiahmed098** [comment]
Hey sorry about that, I completely got sidetracked yesterday. I think listing non-monetary income as `Discount` is non-intuitive, that category should probably be renamed.

I agree with your bullets though, those would probably help to make things a lot clearer for everyone.

**Comment by hadiahmed098** [comment]
I think I will start working on an update to the income area of the system, and keep this issue for tracking changes.
