### ISSUE TITLE
Better backup solution

### ISSUE THREAD

**Issue by rakoskr6** [PurdueIEEE/boilerbooks#23]
Currently daily backups (via cron) are done for the database using mysqldump and all receipts are also saved to a remote server (CSociety). Consider backing up to Drive/Dropbox

**Comment by avaidyam** [comment]
Put simply, a cron job that uses `mysqldump` **is** the best solution. There is an unofficial Google Drive API which I can use to sync the files to drive, but it will end up being a LOT very quickly.

**Comment by rakoskr6** [comment]
It would still be cool to have a better way to view the history of changes. Ie. what was the previous purchase amount of item x before it was updated.

**Comment by avaidyam** [comment]
We're doing something like that. @mattmolo is adding a changelog to purchases and income.

**Comment by mattmolo** [comment]
@rakoskr6 Oh yeah, I was going to add that so anytime purchases, income (maybe budget), gets updated, it would log who did it and the diff.

**Comment by stwrt** [comment]
Currently have a backup solution going again.

Every 24 hours it will dump the current state of ieee-money and pieee and will rsync any new receipts to an offsite backup.
