### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by mattmolo** [PurdueIEEE/boilerbooks#39]
`: set spell` turns on spell check in vim. Is usually handy.
`s/stauts/status/`

https://github.com/rakoskr6/boilerbooks/blob/c3e0fca9b83db7ec0f12a6d9cf75fef75ce3359a/api/approve/index.php#L61

https://github.com/rakoskr6/boilerbooks/blob/c3e0fca9b83db7ec0f12a6d9cf75fef75ce3359a/api/request/index.php#L109

**Comment by rakoskr6** [comment]
I don't use VIM
