### ISSUE TITLE
Support for of .PNG files

### ISSUE THREAD

**Issue by toozinger** [PurdueIEEE/boilerbooks#50]
I noticed today on windows 10 that the snip tool automatically saves images as .PNG files. Would it be easy/able to implement support for these file types?

**Comment by rakoskr6** [comment]
I don't think BOSO accepts png files which is why I don't allow it by default. Now maybe @avaidyam or @mattmolo  could make an automatic converter...

**Comment by avaidyam** [comment]
@rakoskr6 Coming in v2.x, but not v2.0. 👍

**Comment by avaidyam** [comment]
Also, automatic PDF generation and report processing like expensify!
