### ISSUE TITLE
President/Treasurer Fix Request 

### ISSUE THREAD

**Issue by SanayShah96** [PurdueIEEE/boilerbooks#56]
~~Funding Source field add: SOGA~~ (see issue #55)

~~Better sorting on List views~~ (see commit 5b43b8a)

~~Low account balance Warning before it drop below $200 again at $100 and then every purchase from there~~  (see commit 79f9a4a)

~~Negative account balance for below $0~~ (see commit 79f9a4a)

~~Treasurer Tab ability to edit information on UI~~ (see issue #26)

~~Error button in treasurer tab to notify person there is an error in the submission~~ (you have hyperlink of user which contains an email to message them - 2fce67b)

~~Remove refreshing page setup make it normal~~ (see issue #60)

~~Committee tab under Treasurer tab~~ (see commit 967d5a8)

~~Easy to see Account settings button~~ (Done with cb84d3c)

~~Forgot Username?~~ (Done with c4c1ead)

~~Forgot Password?~~ (Done with f95f547)

~~Approve purchase tab make button at bottom say Submit~~ (See d2b28a1)

**Comment by rakoskr6** [comment]
See  my above edits (since someone made 1 giant issue instead of many multiple!)

**Comment by rakoskr6** [comment]
All issue points resolved or referencing another issue
