### ISSUE TITLE
Cannot upload images when completing purchases on iOS

### ISSUE THREAD

**Issue by kingj5** [PurdueIEEE/boilerbooks#71]
Received an error when uploading s receipt. Always seems to happen:

Original date 06-17-2018
Changed date 2018-06-17 00:00:00
There were errors 
'Sorry, there was an error uploading your file.'
'UPDATE Purchases SET modifydate = NOW(), purchasedate='2018-06-17 00:00:00', cost='26.74', status='Purchased', comments='', receipt='money.pieee.org/' WHERE Purchases.purchaseID = '1091'
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'money.pieee.org/' for key 'receipt''

**Comment by brstew** [comment]
Are you only getting this error on iOS? Do you get this same error if you try to upload from a computer?

**Comment by kingj5** [comment]
Downloading the photo from my phone and uploading from my computer works as expected

**Comment by brstew** [comment]
It appears the receipt variable isn't being set correctly. I am not sure what is causing it to fail on iOS if it works on a computer. 🤔

**Comment by erikvanderwerf** [comment]
This is also happening on my Pixel 2 Chrome browser. Possibly a mobile phone thing.

**Comment by mattmolo** [comment]
Can you guys try reuploading your files? The handling of files and error reporting has been redone.

**Comment by erikvanderwerf** [comment]
I was able to upload a smaller image successfully. If I reupload with the original one will that interrupt my transaction?

**Comment by brstew** [comment]
If the transaction successfully went through then you can only update the image by modifying the file on the server. I don't believe changing the picture is currently is possible through the Boilerbooks website.

**Comment by stwrt** [comment]
If this is still an issue please reopen.
