### ISSUE TITLE
Only PDFs and JPEGs are allowed

### ISSUE THREAD

**Issue by erikvanderwerf** [PurdueIEEE/boilerbooks#72]
I am attempting to upload a picture to complete a purchase. I tried to upload a JPEG image and I got the following error:

> Original date 
> Changed date 1969-12-31 19:00:00
> There were errors 
> 'Sorry, only PDFs and JPEGs are allowedSorry, your file was not uploaded.'
> ''

**Comment by erikvanderwerf** [comment]
I rescaled the image and it worked. The original image is 3024x4032 pixels, and is 9 MB. The resized one was 756x1008 and 415KB. If it's a size/resolution image the error should reflect this, otherwise I don't know what it would be.

**Comment by brstew** [comment]
What was the file name you tried to upload?

**Comment by brstew** [comment]
That looks fine 😕

**Comment by brstew** [comment]
I just tested uploading a file with the same name as the Enterprise reimbursement and it successfully went through.

**Comment by rakoskr6** [comment]
@erikvanderwerf was the problem fixed? The limit was changed to 2MB but it sounds like you are under that.

**Comment by erikvanderwerf** [comment]
I was able to resize the images and upload. I don't have any more purchases to test this on.
