### ISSUE TITLE
Treasuerer page refreshes upon purchase update

### ISSUE THREAD

**Issue by rwpearson333** [PurdueIEEE/boilerbooks#89]
Right now when I change the status of a purchase from something like "Processing Reimbursement" -> "Reimbursed" the whole webpage reloads and resets to the default number of items shown, search setting etc. So if I wanted to update 4 items under the search "smith" that on the 3rd page I have to search "smith" and click to the third page for every item.

**Comment by grantg012** [comment]
Send in my dms with Ryan:
My dumb quick fix is that if you middle click and open stuff in a new tab, it doesn't lose the current page/search. It's kinda complex bc the page reloads and when it asks the server for the new page, it tells the server to update the status of the purchase

**Comment by grantg012** [comment]
Idea: embed js to add the purchase to a textbox then have a submit for the textbox to make several as processing/reimbursed https://github.com/PurdueIEEE/boilerbooks/blob/e14c01b852953451913d34eacfddc6ab694d4006/treasurer/index.php#L82
